CALL code --install-extension formulahendry.vscode-mysql
CALL code --install-extension christian-kohler.npm-intellisense
CALL code --install-extension christian-kohler.path-intellisense
CALL code --install-extension CoenraadS.bracket-pair-colorizer
CALL code --install-extension dariofuzinato.vue-peek
CALL code --install-extension dbaeumer.vscode-eslint
CALL code --install-extension eamodio.gitlens
CALL code --install-extension eg2.tslint
CALL code --install-extension eg2.vscode-npm-script
CALL code --install-extension esbenp.prettier-vscode
CALL code --install-extension formulahendry.auto-close-tag
CALL code --install-extension formulahendry.auto-rename-tag
CALL code --install-extension goessner.mdmath
CALL code --install-extension HookyQR.beautify
CALL code --install-extension James-Yu.latex-workshop
CALL code --install-extension Mikael.Angular-BeastCode
CALL code --install-extension ms-python.python
CALL code --install-extension ms-vscode.cpptools
CALL code --install-extension ms-vscode.csharp
CALL code --install-extension ms-vscode.Go
CALL code --install-extension ms-vscode.vs-keybindings
CALL code --install-extension msjsdiag.debugger-for-chrome
CALL code --install-extension mubaidr.vuejs-extension-pack
CALL code --install-extension octref.vetur
CALL code --install-extension PeterJausovec.vscode-docker
CALL code --install-extension PKief.material-icon-theme
CALL code --install-extension quicktype.quicktype
CALL code --install-extension redhat.java
CALL code --install-extension robertohuertasm.vscode-icons
CALL code --install-extension shyykoserhiy.vscode-spotify
CALL code --install-extension SirTori.indenticator
CALL code --install-extension tinkertrain.theme-panda
CALL code --install-extension tombonnike.vscode-status-bar-format-toggle
CALL code --install-extension wayou.vscode-todo-highlight
CALL code --install-extension wix.vscode-import-cost
CALL code --install-extension xabikos.JavaScriptSnippets
CALL code --install-extension yzane.markdown-pdf
