code --install-extension formulahendry.vscode-mysql
code --install-extension christian-kohler.npm-intellisense
code --install-extension christian-kohler.path-intellisense
code --install-extension CoenraadS.bracket-pair-colorizer
code --install-extension dariofuzinato.vue-peek
code --install-extension dbaeumer.vscode-eslint
code --install-extension eamodio.gitlens
code --install-extension eg2.tslint
code --install-extension eg2.vscode-npm-script
code --install-extension esbenp.prettier-vscode
code --install-extension formulahendry.auto-close-tag
code --install-extension formulahendry.auto-rename-tag
code --install-extension goessner.mdmath
code --install-extension HookyQR.beautify
code --install-extension James-Yu.latex-workshop
code --install-extension Mikael.Angular-BeastCode
code --install-extension ms-python.python
code --install-extension ms-vscode.cpptools
code --install-extension ms-vscode.csharp
code --install-extension ms-vscode.Go
code --install-extension ms-vscode.vs-keybindings
code --install-extension msjsdiag.debugger-for-chrome
code --install-extension mubaidr.vuejs-extension-pack
code --install-extension octref.vetur
code --install-extension PeterJausovec.vscode-docker
code --install-extension PKief.material-icon-theme
code --install-extension quicktype.quicktype
code --install-extension redhat.java
code --install-extension robertohuertasm.vscode-icons
code --install-extension shyykoserhiy.vscode-spotify
code --install-extension SirTori.indenticator
code --install-extension tinkertrain.theme-panda
code --install-extension tombonnike.vscode-status-bar-format-toggle
code --install-extension wayou.vscode-todo-highlight
code --install-extension wix.vscode-import-cost
code --install-extension xabikos.JavaScriptSnippets
code --install-extension yzane.markdown-pdf
